name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cat build-rpi-android.sh | docker run --rm -i -v="$PWD/workspace:/workspace" -w="/workspace" openjdk:8-jdk bash
    - name: List files
      run: ls -lh $PWD/workspace
